name       : a2ps
version    : 4.14
release    : 3
source     :
    - https://ftp.gnu.org/gnu/a2ps/a2ps-4.14.tar.gz : f3ae8d3d4564a41b6e2a21f237d2f2b104f48108591e8b83497500182a3ab3a4
license    : GPL-3.0-or-later
component  : programming
summary    : Format files for printing on a PostScript printer
description: |
    a2ps formats files for printing on a PostScript printer.
builddeps  :
    - pkgconfig(ImageMagick)
    - gperf
    - groff
    - psutils
rundeps    :
    - imagemagick
    - psutils
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install

    # Lets discourage things from building against it
    rm -r $installdir/%libdir%
    rm -r $installdir/usr/include
